# Generated by Django 5.1.4 on 2025-01-04 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='고유 ID')),
                ('name', models.CharField(max_length=255, verbose_name='피처 이름')),
                ('importance', models.FloatField(verbose_name='피처 중요도')),
            ],
            options={
                'db_table': 'feature_table',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('date_time', models.DateTimeField(primary_key=True, serialize=False, verbose_name='시간')),
                ('real_price', models.FloatField(verbose_name='실제 가격')),
                ('predicted_price', models.FloatField(null=True, verbose_name='예측 가격')),
            ],
            options={
                'db_table': 'forecast_table',
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='고유 ID')),
                ('class_id', models.CharField(choices=[('news', 'news'), ('reddit', 'reddit')], max_length=10, verbose_name='클래스 ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('sentiment_value', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], max_length=10, verbose_name='감정 분석 결과')),
            ],
            options={
                'db_table': 'sentiment_table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='사용자 이름')),
                ('last_name', models.CharField(max_length=255, verbose_name='사용자 성')),
                ('id', models.CharField(max_length=255, unique=True, verbose_name='사용자 ID')),
                ('password', models.CharField(max_length=255, verbose_name='사용자 비밀번호')),
                ('email', models.EmailField(max_length=255, verbose_name='사용자 이메일')),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url', models.TextField(verbose_name='프로필 이미지 링크')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user', verbose_name='사용자 고유번호')),
            ],
            options={
                'db_table': 'user_profile_table',
            },
        ),
    ]
