# Generated by Django 5.1.4 on 2025-01-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='제목'),
        ),
    ]
